version: '3.3'

services:
  app:
    image: web-back/app:1.0
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file:
      - .env
    volumes:
      - type: bind
        source: .
        target: /web-back
    depends_on:
      - postgres
    command: gunicorn --workers 10 --bind 0.0.0.0:8080 -m 007 wsgi:app

  postgres:
    image: postgres:12.0-alpine
    volumes:
      - type: volume
        source: web-back_pgdata
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
      - type: bind
        source: ./docker/postgres/postgresql.conf
        target: /etc/postgresql.conf
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    command: postgres -c config_file=/etc/postgresql.conf

volumes:
  web-back_pgdata: